-- Documentos identificables del CRM: metadatos restringidos y contenido
-- cifrado en un bucket privado. La clave maestra nunca vive en Postgres.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('secure-documents', 'secure-documents', false, 15728640, ARRAY['application/octet-stream'])
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE TABLE IF NOT EXISTS public.crm_secure_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id uuid NOT NULL REFERENCES public.crm_contactos(id) ON DELETE RESTRICT,
  club text NOT NULL DEFAULT 'Black Gold' CHECK (btrim(club) <> ''),
  document_type text NOT NULL CHECK (document_type IN (
    'consentimiento', 'identidad', 'medico', 'financiero', 'contrato', 'otro'
  )),
  owner_actor text NOT NULL CHECK (owner_actor ~ '^[a-z0-9_-]{2,64}$'),
  classification text NOT NULL DEFAULT 'restringido' CHECK (classification = 'restringido'),
  object_key text NOT NULL UNIQUE CHECK (object_key ~ '^[0-9a-f-]{36}\.bin$'),
  encrypted_dek bytea NOT NULL CHECK (octet_length(encrypted_dek) = 48),
  payload_iv bytea NOT NULL CHECK (octet_length(payload_iv) = 12),
  wrap_iv bytea NOT NULL CHECK (octet_length(wrap_iv) = 12),
  content_sha256 text NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  ciphertext_size bigint NOT NULL CHECK (ciphertext_size BETWEEN 17 AND 15728640),
  mime_type text NOT NULL CHECK (mime_type IN (
    'application/pdf', 'image/jpeg', 'image/png', 'application/octet-stream'
  )),
  retention_until date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_secure_documents_contact
  ON public.crm_secure_documents (contact_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crm_secure_documents_retention
  ON public.crm_secure_documents (retention_until)
  WHERE retention_until IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.crm_secure_document_access (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  secure_document_id uuid REFERENCES public.crm_secure_documents(id) ON DELETE SET NULL,
  actor text NOT NULL CHECK (actor ~ '^[a-z0-9_-]{2,64}$'),
  purpose text NOT NULL CHECK (char_length(btrim(purpose)) BETWEEN 3 AND 240),
  action text NOT NULL CHECK (action IN ('create', 'read_metadata', 'read_content', 'delete')),
  allowed boolean NOT NULL,
  result text NOT NULL CHECK (result IN ('ok', 'denied', 'not_found', 'error')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_secure_access_document
  ON public.crm_secure_document_access (secure_document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crm_secure_access_actor
  ON public.crm_secure_document_access (actor, created_at DESC);

ALTER TABLE public.crm_secure_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_secure_document_access ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.crm_secure_documents FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.crm_secure_document_access FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_secure_documents TO service_role;
GRANT SELECT, INSERT ON public.crm_secure_document_access TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.crm_secure_document_access_id_seq TO service_role;

-- No se crean políticas para storage.objects. Solo el servicio con
-- service_role accede al bucket; los agentes jamás reciben esa credencial.

COMMENT ON TABLE public.crm_secure_documents IS
  'Metadatos de documentos cifrados; no contiene nombres originales ni contenido legible.';
COMMENT ON COLUMN public.crm_secure_documents.encrypted_dek IS
  'DEK aleatoria cifrada con AES-256-GCM por una clave maestra externa.';
COMMENT ON TABLE public.crm_secure_document_access IS
  'Auditoría append-only de cada intento autorizado o denegado.';
