-- STUB de reconciliación de historial (mismo patrón que
-- 20260622000007_migracion_fase1_stub_autor_id.sql).
--
-- El historial server-side registra una migración 20260705224803
-- (2026-07-05 22:48, ~30 min después de v23) aplicada directamente
-- contra la base SIN archivo en el repo — probablemente un ajuste
-- hecho desde el SQL Editor guardado como migración. Su contenido no
-- quedó versionado; si hace falta recuperarlo:
--   SELECT statements FROM supabase_migrations.schema_migrations
--   WHERE version = '20260705224803';  -- (SQL Editor del dashboard)
--
-- Este archivo existe solo para que `supabase db push` no considere
-- divergente el historial. No ejecuta nada a propósito: los cambios
-- reales de esa migración (si los hubo) siguen vigentes en la base y
-- están capturados por el baseline si son de esquema.
SELECT 1;
